[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol = "🅰 "
[aws.region_aliases]
ap-southeast-2 = "au"
us-west-1 = "SFO"
us-west-2 = "PDX"
[directory]
truncation_length = 8
truncation_symbol = "../"
