# Generated by the `theme` skill (theme.py). Do not edit by hand.
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
--color=bg:-1,bg+:#524c46,fg:#beaf93,fg+:#ebdbb2 \
--color=hl:#458588,hl+:#458588,info:#d79921,spinner:#689d6a \
--color=prompt:#d79921,pointer:#689d6a,marker:#98971a,header:#458588 \
--color=border:#928374,label:#beaf93,selected-bg:#786c61"
