# Generated by the `theme` skill (theme.py). Do not edit by hand.
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
--color=bg:-1,bg+:#1a1a1a,fg:#808080,fg+:#c1c1c1 \
--color=hl:#888888,hl+:#888888,info:#a06666,spinner:#aaaaaa \
--color=prompt:#a06666,pointer:#aaaaaa,marker:#dd9999,header:#888888 \
--color=border:#404040,label:#808080,selected-bg:#303030"
