# Generated by the `theme` skill (theme.py). Do not edit by hand.
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
--color=bg:-1,bg+:#bcb5ca,fg:#5b5487,fg+:#9e9eb6 \
--color=hl:#286983,hl+:#286983,info:#ea9d34,spinner:#56949f \
--color=prompt:#ea9d34,pointer:#56949f,marker:#618774,header:#286983 \
--color=border:#5f5695,label:#5b5487,selected-bg:#867eab"
