general.import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]



[window]

padding.x = 18
padding.y = 16
dynamic_padding= false
decorations =  "buttonless"

[font]
normal.family = "FiraCode Nerd Font Mono"
size = 12.0

[terminal.shell]
program = "/bin/zsh"

[keyboard]
bindings = [
    { key = "T", mods = "Command", chars = "\u0000\u0063" },
    { key = "W", mods = "Command", chars = "\u0000x" }, # kill the current pane
    { key = "J", mods = "Command", chars = "\u0000\u0054" }, # open t - tmux smart session manager
    { key = "K", mods = "Command", chars = "\u0000s" }, # open interactive tmux session client
    { key = "Tab", mods = "Control", chars = "\u0000n" }, # switch to next tmux window
    { key = "E", mods = "Command", chars = "\u0000\"" }, # split tmux window vertically
    { key = "E", mods = "Command|Shift", chars = "\u0000%" }, # split tmux window horizontally
    { key = "{", mods = "Command|Shift", chars = "\u0000p" }, # switch to previous tmux window
    { key = "}", mods = "Command|Shift", chars = "\u0000n" }, # switch to next tmux window
    { key = "Comma", mods = "Command", chars = "\u0000," }, # rename the current tmux window
    { key = "Semicolon", mods = "Command", chars = "\u0000:" }, # enter the tmux command prompt
    { key = "S", mods = "Command", chars = "\u0000s" }, # run command
    { key = "N", mods = "Command|Shift", chars = "\u0000:new" }, # create new tmux window
    { key = "R", mods = "Command", chars = "\u0000$" } # rename session
]

[terminal]

